version: '3'

services:
  app:
    build:
      context: .
    tty: False
    ports:
      - '8000:8000'
    volumes:
      - /code/.cache
      - /code/node_modules
      - .:/code
    environment:
      NODE_ENV: development
      GATSBY_WEBPACK_PUBLICPATH: /